### PR TITLE
Profile page

### PR DESCRIPTION
**Pull request by astran20**

### CODE REVIEW

**Comment by astran20** [comment]
dont merge yet

**Comment by axanthus** [comment]
@codespaceDrifter Why did you close and force-push this pr? That's opposite of what I've been saying to do. This isn't even your own pr

**Comment by codespaceDrifter** [comment]
sorry i closed this by mistake i was trying to delete my own branch from history

**Comment by codespaceDrifter** [comment]
sorry i closed this by mistake i was trying to delete my own branch

**Pull request closed without merging**
